version: '2.1'
services:
  bhoutgate:
    build: .
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=:0
      - QT_QPA_PLATFORM=xcb
      - QT_DEBUG_PLUGINS=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: always 