version: '2.1'
services:
  bhoutgate:
    build: .
    privileged: true
    network_mode: host
    environment:
      - UDEV=1
      - QT_QPA_PLATFORM=eglfs
      - QT_DEBUG_PLUGINS=1
    volumes:
      - /dev:/dev
      - /run/udev:/run/udev:ro
    devices:
      - /dev/dri:/dev/dri
    restart: always 